name: Codecov

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34
      - name: Create coverage files
        run: deno test --allow-read --coverage=coverage --lock-write # create coverage files
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov # create coverage report
      - name: Collect coverage
        uses: codecov/codecov-action@v3 # upload the report on Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.lcov
